import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import type { Command } from 'commander';
import { MentuError } from '../types.js';

interface InitClaudeOptions {
  workspace?: string;
  actor?: string;
  force?: boolean;
}

interface InitClaudeOutput {
  created: string[];
  updated: string[];
  config_path: string;
  hooks_path: string;
}

function outputResult(result: InitClaudeOutput, json: boolean): void {
  if (json) {
    console.log(JSON.stringify(result));
  } else {
    console.log('Mentu Claude Code v0.8 initialized');
    console.log('');
    console.log('Created:');
    for (const file of result.created) {
      console.log(`  ${file}`);
    }
    if (result.updated.length > 0) {
      console.log('');
      console.log('Updated:');
      for (const file of result.updated) {
        console.log(`  ${file}`);
      }
    }
    console.log('');
    console.log('Hooks wired in Claude Code settings:');
    console.log('  - SessionStart: Injects claimed commitments into agent context');
    console.log('  - PostToolUse (Edit|Write): Auto-captures file edits as evidence');
    console.log('');
    console.log('Permissions added:');
    console.log('  - Bash(mentu:*) — allows mentu CLI commands');
    console.log('');
    console.log('Workflow:');
    console.log('  1. mentu commit "Task" --source mem_xxx');
    console.log('  2. mentu claim cmt_xxx');
    console.log('  3. Work (edits auto-captured as evidence)');
    console.log('  4. mentu submit cmt_xxx --summary "Done"');
  }
}

function outputError(error: MentuError, json: boolean): void {
  if (json) {
    console.log(JSON.stringify(error.toJSON()));
  } else {
    console.error(`Error: ${error.message}`);
  }
  process.exit(1);
}

export function registerInitClaudeCommand(program: Command): void {
  program
    .command('init-claude')
    .description('Initialize Mentu integration for Claude Code')
    .option('-w, --workspace <id>', 'Workspace ID')
    .option('-a, --actor <name>', 'Actor identity', 'agent:claude-code')
    .option('-f, --force', 'Overwrite existing files')
    .action((options: InitClaudeOptions) => {
      const json = program.opts().json || false;

      try {
        const projectRoot = process.cwd();
        const claudeDir = path.join(projectRoot, '.claude');
        const hooksDir = path.join(claudeDir, 'hooks');

        // Check for existing integration
        const configPath = path.join(claudeDir, 'mentu_config.yaml');
        if (fs.existsSync(configPath) && !options.force) {
          throw new MentuError(
            'E_WORKSPACE_EXISTS',
            'Mentu Claude integration already exists. Use --force to overwrite.'
          );
        }

        // Create directories
        fs.mkdirSync(hooksDir, { recursive: true });

        const created: string[] = [];

        // Find template files
        // In ESM, we need to resolve the path from the current module
        const __filename = fileURLToPath(import.meta.url);
        const __dirname = path.dirname(__filename);

        // Templates are in src/templates/ relative to dist/commands/
        // After build: dist/commands/init-claude.js -> src/templates/
        const mentuRoot = path.resolve(__dirname, '..', '..');
        const templatesDir = path.join(mentuRoot, 'src', 'templates');

        // Copy hook templates (v0.7 MVP hooks)
        const hookFiles = [
          'mentu_session_start.py',
          'mentu_post_tool.py'
        ];

        for (const hookFile of hookFiles) {
          const srcPath = path.join(templatesDir, 'hooks', hookFile);
          const destPath = path.join(hooksDir, hookFile);

          if (fs.existsSync(srcPath)) {
            fs.copyFileSync(srcPath, destPath);
            fs.chmodSync(destPath, 0o755); // Make executable
          } else {
            // Fallback: create minimal placeholder
            fs.writeFileSync(destPath, `#!/usr/bin/env python3\n# ${hookFile}\n# Run: mentu init-claude to regenerate\n`);
            fs.chmodSync(destPath, 0o755);
          }
          created.push(`.claude/hooks/${hookFile}`);
        }

        // Create config
        const config = `# Mentu Integration for Claude Code v0.7 MVP
# Generated by: mentu init-claude
# Philosophy: Enforcement, not creation. Presence, not intelligence.

hooks:
  mentu:
    enabled: true
    actor: "${options.actor || 'agent:claude-code'}"
    workspace_id: "${options.workspace || '${MENTU_WORKSPACE_ID}'}"

    # v0.7 MVP Hooks:
    # - mentu_session_start.py: Injects claimed commitments at session start
    # - mentu_post_tool.py: Auto-captures file edits as evidence

    # The agent MUST manually:
    # - mentu submit <cmt> --summary "..." to close commitments
    # - The enforcer hook (if active) blocks stop until commitments are closed
`;
        fs.writeFileSync(configPath, config);
        created.push('.claude/mentu_config.yaml');

        // Update .gitignore
        const gitignorePath = path.join(projectRoot, '.gitignore');
        const mentuEntry = '\n# Mentu state\n.claude/mentu_state.json\n.claude/mentu_evidence.json\n';

        if (fs.existsSync(gitignorePath)) {
          const content = fs.readFileSync(gitignorePath, 'utf-8');
          if (!content.includes('mentu_state.json') && !content.includes('mentu_evidence.json')) {
            fs.appendFileSync(gitignorePath, mentuEntry);
          }
        }

        // Wire hooks into Claude Code settings.json
        const updated: string[] = [];
        const settingsPath = path.join(claudeDir, 'settings.json');
        let settings: Record<string, unknown> = {};

        if (fs.existsSync(settingsPath)) {
          try {
            settings = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
          } catch {
            settings = {};
          }
        }

        // Ensure hooks section exists
        if (!settings.hooks || typeof settings.hooks !== 'object') {
          settings.hooks = {};
        }
        const hooks = settings.hooks as Record<string, unknown[]>;

        // Add SessionStart hook (injects claimed commitments)
        const sessionStartHook = {
          matcher: '',
          hooks: [{
            type: 'command',
            command: '"$CLAUDE_PROJECT_DIR"/.claude/hooks/mentu_session_start.py',
            timeout: 15
          }]
        };

        if (!hooks.SessionStart) {
          hooks.SessionStart = [];
        }
        const sessionHooks = hooks.SessionStart as Record<string, unknown>[];
        const hasSessionHook = sessionHooks.some((h) =>
          JSON.stringify(h).includes('mentu_session_start')
        );
        if (!hasSessionHook) {
          sessionHooks.push(sessionStartHook);
        }

        // Add PostToolUse hook (auto-captures file edits)
        const postToolHook = {
          matcher: 'Edit|Write',
          hooks: [{
            type: 'command',
            command: '"$CLAUDE_PROJECT_DIR"/.claude/hooks/mentu_post_tool.py',
            timeout: 15
          }]
        };

        if (!hooks.PostToolUse) {
          hooks.PostToolUse = [];
        }
        const postHooks = hooks.PostToolUse as Record<string, unknown>[];
        const hasPostHook = postHooks.some((h) =>
          JSON.stringify(h).includes('mentu_post_tool')
        );
        if (!hasPostHook) {
          postHooks.push(postToolHook);
        }

        // Ensure mentu CLI permission is allowed
        if (!settings.permissions || typeof settings.permissions !== 'object') {
          settings.permissions = {};
        }
        const permissions = settings.permissions as Record<string, unknown>;
        if (!Array.isArray(permissions.allow)) {
          permissions.allow = [];
        }
        const allowList = permissions.allow as string[];
        if (!allowList.includes('Bash(mentu:*)')) {
          allowList.push('Bash(mentu:*)');
        }

        fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n');
        updated.push('.claude/settings.json');

        const result: InitClaudeOutput = {
          created,
          updated,
          config_path: configPath,
          hooks_path: hooksDir,
        };

        outputResult(result, json);
      } catch (err) {
        if (err instanceof MentuError) {
          outputError(err, json);
        } else {
          const error = new MentuError(
            'E_INVALID_OP',
            err instanceof Error ? err.message : 'Unknown error'
          );
          outputError(error, json);
        }
      }
    });
}
